name: Setup AWS CLI
description: Install and configure the AWS CLI for deployment workflows.
inputs:
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-default-region:
    description: AWS default region
    required: true

runs:
  using: composite
  steps:
    - name: Install AWS CLI
      shell: bash
      run: |
        sudo apt-get install -y python3-pip
        pip3 install awscliv2

    - name: Configure AWS Credentials
      shell: bash
      env:
        INPUT_AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        INPUT_AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        INPUT_AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
      run: |
        aws configure set aws_access_key_id "$INPUT_AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$INPUT_AWS_SECRET_ACCESS_KEY"
        aws configure set default.region "$INPUT_AWS_DEFAULT_REGION"
