RailsLambda:
  Type: AWS::Serverless::Function
  Metadata:
    DockerContext: .
    Dockerfile: Dockerfile
    DockerTag: web
  Properties:
    AutoPublishAlias: live
    FunctionUrlConfig:
      AuthType: NONE
    DeploymentPreference:
      Type: AllAtOnce
    MemorySize: 1792
    PackageType: Image
    Timeout: 30