services:
  app:
    build: { context: ., dockerfile: Dockerfile }
    command: sleep infinity
    privileged: true
    environment:
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD=root
    depends_on:
      pgsql: { condition: service_healthy }
  pgsql:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ps
    volumes: ["data-mysql:/var/lib/mysql"]
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 10s
    timeout: 5s
    retries: 5
volumes:
  data-postgres: