# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93273caae75b3c8f12d8274defc2c07f85557e08d63d2a232ed8e0624ac3164ed0ac38b3016042f0e8f82891d775035bca88bceb5e7c8785f01803c132d13367

test:
  secret_key_base: ac5acbcce65ec8e766e75eee2312f84d82342fdc91880b454267cc664c75bca074d90559fa9246b69acc95a33df38a499b213c87650724c6ab095c85c013c6c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
