version: "3"
services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
networks:
  app:
    driver: bridge
