source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '>= 7.1.2', '< 8.0'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
# gem 'sdoc', group: :doc

gem 'haml-rails', '~> 2.0.0'
gem 'bootstrap', '4.2.1'
gem "font-awesome-sass", "~> 6.5.1"
gem "devise", ">= 4.9.2"
gem 'nokogiri'
gem 'geocoder'
gem 'omniauth-facebook'
gem 'puma', "=6.2.2"
gem 'amazon-ecs'
gem 'staccato'
gem 'pg'
gem 'listen'
gem "webpacker", '>= 6.0.0.rc.6'
gem "sprockets-rails"
gem "omniauth-rails_csrf_protection"
gem 'bourbon'
gem 'autoprefixer-rails'

group :production do
  gem 'rails_12factor'
  gem 'aws_lambda_ric'
end

group :development, :test do
  gem 'rails-controller-testing'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring' , '~> 1.3.2'
  gem 'capybara'
  gem 'pry'
end
ruby '3.2.2'
