name: Deploy-Staging

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: deploy-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/test-suite.yml

  deploy:
    needs: tests
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/deploy-app.yml
    with:
      stack_name: RailsLambdaStack
      cloudfront_distribution_id: E2J7FXI85QUSUM
      robots_source: robots.txt.staging
      recache_urls_file: urls-staging.txt
    secrets: inherit
