name: PR Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
      - "deployment/**"
      - "mcp-server/**"
      - ".github/workflows/pr-tests.yml"
      - ".github/workflows/test-suite.yml"

jobs:
  tests:
    uses: ./.github/workflows/test-suite.yml
