name: schengtrackStageTests

on:
  push:
    branches:
      - cdkLambdaDeployFinal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Change to Source directory
        run: cd src

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d
        working-directory: src

      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: 3.2.1

      - run: rails db:create
        working-directory: src

      - run: rails db:migrate
        working-directory: src

      - run: bundle install
        working-directory: src

      - run: bundle exec rake
        working-directory: src
